services:
  webapp:
    build:
        context: .
        dockerfile: "./docker/Dockerfile.node"
    ports:
      - "3000:3000"
    networks:
      - ollama
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
    command: "npm run dev"
    profiles:
      - all

  python:
    build:
        context: .
        dockerfile: "./docker/Dockerfile.python"
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama
    env_file:
      - .env.local
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
    profiles:
      - all

  ollama:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.ollama"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Uncomment this section to run on a compatible nvidia GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         capabilities: ["gpu"]
    #         count: all

volumes:
  ollama_data:
networks:
  ollama: