FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY .env.local ./
COPY ./python ./python
COPY ./tests ./tests

RUN chmod +x ./python/ingest/scraper.py